### ISSUE TITLE
error when running

### ISSUE THREAD

**Issue by RaitonGG** [vinsce/gneelight#3]
i'm new to linux and never coded in python,

since I could not find a way to use the flatpack on ubuntu 20.04. I tried downloading the src and running the py file. however I get this error

`python3 GneelightApp.py
Traceback (most recent call last):
  File "GneelightApp.py", line 7, in <module>
    from MainWindow import MainWindow
  File "/home/raiton/Documents/software/gneelight-master/src/MainWindow.py", line 7, in <module>
    gi.require_version('AppIndicator3', '0.1')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available
raiton@raitons-laptop:~/Documents/software/gneeligh`

**Comment by RaitonGG** [comment]
turns out I missing a package.

`sudo apt install gir1.2-appindicator3-0.1`

solves this. however I got a new error now

`python3 GneelightApp.py
Traceback (most recent call last):
  File "GneelightApp.py", line 7, in <module>
    from MainWindow import MainWindow
  File "/home/raiton/Documents/software/gneelight-master/src/MainWindow.py", line 9, in <module>
    from BulbWrapper import BulbWrapper, ColorModes, Effect
  File "/home/raiton/Documents/software/gneelight-master/src/BulbWrapper.py", line 4, in <module>
    from yeelight import Bulb, discover_bulbs
ModuleNotFoundError: No module named 'yeelight'
`

**Comment by vinsce** [comment]
Hi @RaitonGG , it seems that you are missing the [yeelight](https://github.com/skorokithakis/python-yeelight) library that is required by Gneelight.

You can install it using pip:
```bash
pip install yeelight
```
